controller_manager:
  ros__parameters:
    update_rate: 1000

    Five_DoF_controller:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

Five_DoF_controller:
  ros__parameters:
    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5


    allow_partial_joints_goal: true
