controller_manager:
  ros__parameters:
    update_rate: 1000
  
  joint_trajectory_controller:
    type: joint_trajectory_controller/JointTrajectoryController

  
  joint_state_broadcaster:
    type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      - effort

    joints:
      - joint_1
      - joint_2
      - joint_3
